---
#
# for ubuntu lts
#
# lsb_release -a
#  Distributor ID:	Ubuntu
#  Description:	Ubuntu 14.04.3 LTS
#  Release:	14.04
#  Codename:	trusty
#
#
#


# application

application_domain: "domain.tld"
application_name: "domain_tld"
application_dir: "/opt/{{ application_name }}"
application_user: "appuser"
application_git_repository: "git@github.com:user/repo.git"
application_git_branch: "master"
application_env: production # or dev
application_gis: false
application_packages:
  - build-essential
  - git
  - python3
  - python3-dev
  - python3-setuptools
  - python3-psycopg2
  - python-virtualenv
  - python3-pip
  - libpq-dev
  - libmysqlclient-dev
  # for pillow
  - libtiff5-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libfreetype6-dev
  - liblcms2-dev
  - libwebp-dev
  - tcl8.6-dev
  - tk8.6-dev
  - python-tk
  - python3-tk
  #
  - supervisor
  - iptables-persistent

application_virtualenv_dir: "{{ application_dir }}/.venv"
application_virtualenv_requirements:
  - "{{ application_dir }}/src/requirements.txt"

application_virtualenv_extra_packages:
 - hiredis
 - django-redis-cache
 - django-redis-sessions


application_db_engine: "django.db.backends.postgresql"
application_gis_db_engine: "django.contrib.gis.db.backends.postgis"

application_db_port: 5432
application_db_name: "{{ application_name }}"
application_db_user: "{{ application_user }}"
application_db_password: "12345"

application_ssh_known_hosts:
  - github.com
  - bitbucket.org

application_nodejs_deploy: false
application_nodejs_version: "5.x"

# django
django_dir: "{{ application_dir }}/src"
django_secret_key: 1wkfhsdjhfksdjhfksdjhfkdsjhfkjdsahfkjshas
django_debug: "false"
local_dev: "false"


# gunicorn
gunicorn_workers: 2
gunicorn_log_level: debug
gunicorn_port: "9000"
gunicorn_bind_to_public: false

# supervisor


# postgresql
postgresql_db_name: "{{ application_db_name }}"
postgresql_db_user: "{{ application_db_user }}"
postgresql_db_password: "{{ application_db_password }}"
postgresql_db_port: "{{ application_db_port }}"
postgresql_packages:
  - build-essential
  - postgresql
  - python-dev
  - python-setuptools
  - python-psycopg2
  - postgresql
  - postgresql-contrib
  - postgresql-doc
  - libpq-dev
postgresql_version: "9.3"
postgresql_postgis_enabled: "{{ application_gis }}"
postgresql_postgis_repository: "ppa:ubuntugis/ubuntugis-unstable"
postgresql_postgis_packages:
    - postgresql-9.3-postgis-2.1
    - proj-bin
    - gdal-bin
    - libgeos-3.4.2


# nginx
nginx_packages:
  - build-essential
  - nginx-extras
nginx_log_dir: "{{ application_dir }}/log"
nginx_ssl_dir: "/etc/nginx/ssl"
nginx_ssl_only: false
nginx_use_secure_link: false
nginx_ssl_cert_file: "{{ nginx_ssl_dir }}/{{ application_name }}.cert"
nginx_ssl_key_file: "{{ nginx_ssl_dir }}/{{ application_name }}.key"

# RSYNC NOTATION !!!! BE CAREFUL!
# src=/dir1 dst=/dir2 - synced dir1 into /dir2/dir1
# src=/dir1/* dst=/dir2 - synced dir1 into /dir2/
nginx_sync_public_dir: false
# on local machine
nginx_public_src_dir: "{{ application_dir }}/public/media"
# on remote
nginx_public_dst_dir: "{{ application_dir }}/public/"
# if this is set the source will be this host not a local machine
nginx_public_src_host: ""
#
nginx_default_server: false

nginx_ssl_key: |
  ssl certificate, set it in your inventory/group_vars/(all|whatever)/private.yml
nginx_ssl_cert: |
  ssl certificate's private key, set it in your inventory/group_vars/(all|whatever)/private.yml


# redis
redis_packages:
  - redis-server
redis_port: 6379
redis_id: 1
redis_password: ""

# rabbitmq


# celery


# git keys

git_rsa_pub: "rsa public key to access git repo, set it in your inventory/group_vars/(all|whatever)/private.yml"
git_rsa_key: |
  rsa private key to access git repo, set it in your inventory/group_vars/(all|whatever)/private.yml
